name: push-to-dockerhub

description: Copy common scripts into features

runs:
  using: composite
  steps:
    - shell: bash
      name: Copy common scripts into features
      run: |
        find ./features/src -mindepth 1 -maxdepth 1 -type d -exec \
          bash -c 'rm -rf {}/common && cp -ar ./features/common {}/' \;
