name: feature-matrix

description: Determine the feature matrix

inputs:
  full_matrix:
    type: string
    default: 'false'

outputs:
  features:
    value: ${{ steps.matrix.outputs.features }}
  scenarios:
    value: ${{ steps.matrix.outputs.scenarios }}

runs:
  using: composite
  steps:
    - id: get-pr-info
      if: inputs.full_matrix != 'true'
      name: Get last successful main commit sha
      uses: ./.github/actions/get-pr-info

    - name: Check if files changed
      if: inputs.full_matrix != 'true'
      id: changes
      uses: tj-actions/changed-files@v35.4.4
      with:
        base_sha: ${{ fromJSON(steps.get-pr-info.outputs.pr-info).base.sha }}
        files: |
          features/src/**
          features/test/**
          .github/workflows/test.yml
          .github/workflows/build-and-test-feature.yml
          .github/actions/build-and-test-feature/action.yml
        #  .github/actions/feature-matrix/action.yml

    - name: Report changes
      if: inputs.full_matrix != 'true'
      shell: bash
      run: echo '${{ toJSON(steps.changes.outputs) }}'

    - name: Determine the feature matrix
      id: matrix
      shell: bash --noprofile --norc -x -eo pipefail {0}
      run: |
        .github/actions/feature-matrix/action.sh \
          '${{ inputs.full_matrix }}' \
          '${{ steps.changes.outputs.all_changed_and_modified_files }}' \
        | tee -a $GITHUB_OUTPUT;
