name: feature-matrix

description: Determine the feature matrix

outputs:
  features:
    value: ${{ steps.matrix.outputs.features }}
  scenarios:
    value: ${{ steps.matrix.outputs.scenarios }}

runs:
  using: composite
  steps:
    - name: Determine the feature matrix
      id: matrix
      shell: bash
      run: |
        join_with_delimiter() {
          local IFS='' delim=$1; shift; echo -n "$1"; shift; echo -n "${*/#/$delim}";
        }

        features="$(                                                       \
          find ./features/test -mindepth 1 -type f -name test.sh -exec     \
            bash -c 'echo {} | sed -r s@./features/test/\(.*\)/.*@\\1@' \; \
        | grep -v _global                                                  \
        )";

        if [[ -n "$(echo "$features")" ]]; then
          features="[\"$(join_with_delimiter '","' $features)\"]";
        fi

        echo "features=${features:-'[]'}" | tee -a $GITHUB_OUTPUT;

        scenarios="$(                                                         \
          find ./features/test -mindepth 1 -type f -name scenarios.json -exec \
            bash -c 'echo {} | sed -r s@./features/test/\(.*\)/.*@\\1@' \;    \
        | grep -v _global                                                     \
        )";

        if [[ -n "$(echo "$scenarios")" ]]; then
          scenarios="[\"$(join_with_delimiter '","' $scenarios)\"]";
        fi

        echo "scenarios=${scenarios:-'[]'}" | tee -a $GITHUB_OUTPUT;
