name: image-matrix

description: Determine the image matrix

outputs:
  matrix:
    value: ${{ steps.matrix.outputs.matrix }}

runs:
  using: composite
  steps:
    - name: Determine the image matrix
      id: matrix
      shell: bash
      run: |
        echo "matrix=$(\
          cat ./images/matrix.yml \
        | yq -o json --no-colors  \
        | jq -c -r -M '.matrix'   \
        )" | tee -a $GITHUB_OUTPUT;
