name: image-matrix

description: Determine the image matrix

inputs:
  features:
    type: string
    required: false
  scenarios:
    type: string
    required: false

outputs:
  matrix:
    value: ${{ steps.matrix.outputs.matrix }}

runs:
  using: composite
  steps:
    - name: Determine the image matrix
      id: matrix
      shell: bash
      run: |
        set -x;

        filter="$(echo                                             \
          '"${{ join(fromJSON(inputs.features  || '[]'), '|') }}"' \
          '"${{ join(fromJSON(inputs.scenarios || '[]'), '|') }}"' \
        | jq -sr 'map(select(. != "")) | join("|")'                \
        )";

        cmd="$([ -z "$filter" ]     \
        && echo cat                 \
        || echo grep -E "($filter)" \
        )";

        cat <<EOF | yq -o json --no-colors   \
                  | jq -c -r -M '.matrix'    \
                  | cat <(echo -n matrix=) - \
                  | tee -a $GITHUB_OUTPUT
        matrix:
          include:
        $($cmd ./images/matrix.yml         \
        | xargs -r -d'\n' -I{} echo '  {}' \
        )
        EOF
