name: image-matrix

description: Determine the image matrix

inputs:
  features:
    type: string
    required: false
  scenarios:
    type: string
    required: false

outputs:
  matrix:
    value: ${{ steps.matrix.outputs.matrix }}

runs:
  using: composite
  steps:
    - name: Determine the image matrix
      id: matrix
      shell: bash
      env:
        features: "${{ join(fromJSON(inputs.features || '[]'), '|') }}"
        scenarios: "${{ join(fromJSON(inputs.scenarios || '[]'), '|') }}"
      run: |
        set -x;

        filter="";

        if [[ -n "$features" && -n "$scenarios" ]]; then
          filter="(${{ join([env.features, env.scenarios], '|') }})";
        elif [[ -n "$features" ]]; then
          filter="($features)";
        elif [[ -n "$scenarios" ]]; then
          filter="($scenarios)";
        fi

        cmd="$([ -x "$filter" ]     \
        && echo "cat"               \
        || echo "grep -E '$filter'" \
        )";

        echo "matrix=$(            \
          $cmd ./images/matrix.yml \
        | yq -o json --no-colors   \
        | jq -c -r -M '.matrix'    \
        )" | tee -a $GITHUB_OUTPUT ;
