name: image-info

description: Setup self-hosted runner environment

inputs:
  arch:
    type: string
    required: true

runs:
  using: composite
  steps:
    - if: contains(runner.name, 'rapidsai') == true
      name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Setup self-hosted runner environment
      if: contains(runner.name, 'rapidsai') == true
      shell: bash -xeo pipefail {0}
      run: |
        echo "${{ toJSON(runner) }}";

        USER="$(whoami)";
        TMPDIR="${{ runner.temp }}";
        NEW_HOME="${{ runner.workspace }}";
        OLD_HOME="$(bash -c "echo ~${USER}")";
        sudo sed -ri "s@$OLD_HOME@$NEW_HOME@g" /etc/passwd

        echo "HOME=$NEW_HOME" >> $GITHUB_ENV;
        echo "TMPDIR=$TMPDIR" >> $GITHUB_ENV;

        mkdir -p "$NEW_HOME/.docker/cli-plugins";
        curl -s \
            -L "https://github.com/docker/buildx/releases/download/v0.10.1/buildx-v0.10.1-linux-${{ inputs.arch }}" \
            -o "$NEW_HOME/.docker/cli-plugins/buildx";

        chmod +x "$NEW_HOME/.docker/cli-plugins/buildx";
        stat "$NEW_HOME/.docker/cli-plugins/buildx";

        which -a docker;
        docker --version;
        docker buildx version;
        docker buildx && echo $?;
