name: image-info

description: Setup self-hosted runner environment

runs:
  using: composite
  steps:
    - if: contains(runner.name, 'rapidsai') == true
      name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Setup self-hosted runner environment
      if: contains(runner.name, 'rapidsai') == true
      shell: bash --noprofile --norc -xeo pipefail {0}
      run: |
        echo "${{ toJSON(runner) }}";

        cd "${{ runner.workspace }}/devcontainers";
        mkdir -p "./_temp";

        # echo "TMPDIR=./_temp" >> $GITHUB_ENV;
        # echo "HOME=${{ runner.workspace }}" >> $GITHUB_ENV;

        # find "${{ runner.workspace }}" -type d;

        # echo "TMPDIR=/data/_temp" >> $GITHUB_ENV;
        # echo "HOME=/data/devcontainers" >> $GITHUB_ENV;

        # data="${{ runner.workspace }}/../";
        # data="$(realpath -m "$data")";
        # sudo ln -s "$data" "/data";
        # sudo ln -s "$(realpath -m ../../)" /data;

        # sudo chown -R $(id -u):$(id -g) "/data";
        # sudo chown -R $(id -u):$(id -g) "$data";

        # find /data/ -type d;
        # find $data/ -type d;

        echo "container workspace:"
        find "${{ runner.workspace }}" -type d;

        echo "host root:"
        docker run --rm -v "/:/host" ubuntu:jammy find /host -type d;
