name: image-info

description: Setup self-hosted runner environment

inputs:
  arch:
    type: string
    required: true

runs:
  using: composite
  steps:
    - if: contains(runner.name, 'rapidsai') == true
      name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Setup self-hosted runner environment
      if: contains(runner.name, 'rapidsai') == true
      shell: bash -xeo pipefail {0}
      run: |
        echo "${{ toJSON(runner) }}";

        echo "HOME=${{ runner.workspace }}" >> $GITHUB_ENV;
        echo "TMPDIR=${{ runner.temp }}" >> $GITHUB_ENV;

        HOME="$(bash -c "echo ~$(whoami)")";
        mkdir -p "$HOME/.docker/cli-plugins";
        chmod 0775 "$HOME/.docker/cli-plugins";
        chmod 0700 "$HOME/.docker";
        curl -s \
            -L "https://github.com/docker/buildx/releases/download/v0.10.1/buildx-v0.10.1.linux-${{ inputs.arch }}" \
            -o "$HOME/.docker/cli-plugins/buildx";

        chmod 0755 "$HOME/.docker/cli-plugins/buildx";

        stat "$HOME/.docker";
        stat "$HOME/.docker/cli-plugins";
        stat "$HOME/.docker/cli-plugins/buildx";

        which -a docker;
        docker --version;
        docker buildx version;
