name: setup-runner-env

description: Setup self-hosted runner environment

inputs:
  runner_env: {type: string, default: '', required: false}

runs:
  using: composite
  steps:
    - name: Dump environment
      shell: bash -eo pipefail {0}
      run: |
        echo "env: ${{ toJSON(env) }}"
        echo "inputs.runner_env: "${{ inputs.runner_env }}""

    - if: inputs.runner_env != 'self-hosted'
      name: Free up disk space
      uses: ./.github/actions/free-disk-space
      with:
        tool_cache: "${{ runner.tool_cache }}"

    - if: inputs.runner_env == 'self-hosted'
      name: Setup self-hosted runner environment
      shell: bash -eo pipefail {0}
      run: |
        echo "HOME=${{ runner.workspace }}" >> $GITHUB_ENV;
        echo "TMPDIR=${{ runner.temp }}" >> $GITHUB_ENV;

    - if: inputs.runner_env == 'self-hosted'
      name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - if: inputs.runner_env != 'self-hosted'
      name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Create docker context
      shell: bash
      run: docker context create builder

    - if: inputs.runner_env != 'self-hosted'
      name: Setup docker buildx on github-hosted runners
      uses: docker/setup-buildx-action@v2
      with:
        buildkitd-flags: --debug
        endpoint: builder

    - if: inputs.runner_env == 'self-hosted'
      name: Setup docker buildx on self-hosted runners
      uses: docker/setup-buildx-action@v2
      with:
        buildkitd-flags: --debug --config /etc/buildkit/buildkitd.toml
        endpoint: builder
        config: /etc/buildkit/buildkitd.toml
