name: image-info

description: Setup self-hosted runner environment

runs:
  using: composite
  steps:
    - if: contains(runner.name, 'rapidsai') == true
      name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Setup self-hosted runner environment
      if: contains(runner.name, 'rapidsai') == true
      shell: bash -xeo pipefail {0}
      run: |
        echo "${{ toJSON(runner) }}";
        echo "TMPDIR=${{ runner.temp }}" >> $GITHUB_ENV;
        echo "HOME=${{ runner.workspace }}" >> $GITHUB_ENV;
