name: image-info

description: Determine devcontainer image info

inputs:
  CPP:
    type: string
    required: true
  CUDA:
    type: string
    required: true
  LLVM:
    type: string
    required: true
  RUST:
    type: string
    required: true
  NVHPC:
    type: string
    required: true
  MAMBA:
    type: string
    required: true

outputs:
  dir:
    value: ${{ steps.image-info.outputs.dir }}
  tag:
    value: ${{ steps.image-info.outputs.tag }}

runs:
  using: composite
  steps:
    - id: image-info
      name: Determine devcontainer image info
      shell: bash
      env:
        CPP: "${{ inputs.CPP }}"
        CUDA: "${{ inputs.CUDA }}"
        LLVM: "${{ inputs.LLVM }}"
        RUST: "${{ inputs.RUST }}"
        NVHPC: "${{ inputs.NVHPC }}"
        MAMBA: "${{ inputs.MAMBA }}"
      run: |
        join_with_delimiter() {
          local IFS='' delim=$1; shift; echo -n "$1"; shift; echo -n "${*/#/$delim}";
        }

        dir="$(join_with_delimiter "-" \
          ${CPP:+"cpp"} \
          ${LLVM:+"llvm"} \
          ${RUST:+"rust"} \
          ${CUDA:+"cuda"} \
          ${MAMBA:+"mambaforge"} \
          ${NVHPC:+"nvhpc"} \
        )";

        if [[ ! -d "./images/${dir}" ]]; then
          echo "skipping because ! -d ./images/${dir}";
          exit 1;
        fi

        RAPIDS="$(git describe --abbrev=0 --tags | sed 's/[a-zA-Z]//g' | cut -d '.' -f -2)";

        tag="$(join_with_delimiter "-" \
          ${RAPIDS:-dev} \
          ${CPP:-} \
          ${LLVM:-} \
          ${RUST:-} \
          ${CUDA:-} \
          ${MAMBA:-} \
          ${NVHPC:-} \
        )";

        echo "dir=$dir" >> $GITHUB_OUTPUT;
        echo "tag=$tag" >> $GITHUB_OUTPUT;

        sed -i -re \
          "s@features/cuda(:[0-9]+)?\": \{\}@features/cuda\1\": \{\"version\": \"${CUDA#cuda}\"\}@" \
          "./images/${dir}/.devcontainer/devcontainer.json";
        sed -i -re \
          "s@features/llvm(:[0-9]+)?\": \{\}@features/llvm\1\": \{\"version\": \"${LLVM#llvm}\"\}@" \
          "./images/${dir}/.devcontainer/devcontainer.json";
        sed -i -re \
          "s@features/nvhpc(:[0-9]+)?\": \{\}@features/nvhpc\1\": \{\"version\": \"${NVHPC#nvhpc}\"\}@" \
          "./images/${dir}/.devcontainer/devcontainer.json";

        echo "image name: ghcr.io/${{ github.repository_owner }}/devcontainers:${tag}";
        echo "devcontainer.json:";
        cat "./images/${dir}/.devcontainer/devcontainer.json";
