name: push-to-dockerhub

description: Install devcontainers CLI

runs:
  using: composite
  steps:
    - name: Install devcontainers CLI
      # run: npm install -g @devcontainers/cli
      shell: bash
      run: |
        sudo wget --no-hsts -q -O /usr/bin/devcontainer \
          "https://github.com/trxcllnt/devcontainers-cli/releases/download/v0.29.0-trxcllnt/devcontainer-linux-x64";
        sudo chmod +x /usr/bin/devcontainer;
