name: build-image

description: Build Linux image

inputs:
  runner_env: {type: string, default: '', required: false}
  tag: {type: string, required: true, description: Image tag}
  arch: {type: string, required: true, description: Image arch}
  repo: {type: string, required: true, description: Image repo}

runs:
  using: composite
  steps:

    - name: Setup runner environment
      uses: ./.github/actions/setup-runner-env
      with:
        runner_env: ${{ inputs.runner_env }}

    - name: Copy common scripts into features
      uses: ./.github/actions/copy-common-scripts

    - name: Install devcontainers CLI
      uses: ./.github/actions/install-devcontainers-cli

    - id: build
      name: Build ${{ inputs.repo }}:${{ inputs.tag }}-${{ inputs.arch }}
      shell: bash
      env:
        NODE_NO_WARNINGS: 1
        repo: ${{ inputs.repo }}
      run: |
        devcontainer build \
          --platform "linux/${{ inputs.arch }}" \
          --cache-from "${repo,,}:${{ inputs.tag }}" \
          --image-name "${repo,,}:${{ inputs.tag }}" \
          --workspace-folder "$(realpath -m ./image)" \
          --output "type=docker,dest=${{ runner.temp }}/${{ inputs.arch }}.tar" \
          ;
