name: build-and-push-image

description: Build and push image

inputs:
  dir:
    type: string
    required: true
    description: Image dir
  tag:
    type: string
    required: true
    description: Image tag
  arch:
    type: string
    required: true
    description: Image arch
  repository:
    type: string
    required: true
    description: Docker Hub repository

runs:
  using: composite
  steps:

    - name: Setup runner environment
      uses: ./.github/actions/setup-runner-env

    - name: Copy common scripts into features
      uses: ./.github/actions/copy-common-scripts

    - name: Install devcontainers CLI
      uses: ./.github/actions/install-devcontainers-cli

    - name: Login to ghcr.io
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ github.token }}

    - name: Build and push ghcr.io/${{ github.repository_owner }}/devcontainers:${{ inputs.tag }}-${{ inputs.arch }}
      uses: devcontainers/ci@v0.2
      env:
        NODE_NO_WARNINGS: 1
      with:
        push: always
        skipContainerUserIdUpdate: true
        subFolder: images/${{ inputs.dir }}
        imageName: ghcr.io/${{ github.repository_owner }}/devcontainers
        imageTag: ${{ inputs.tag }}-${{ inputs.arch }}
        cacheFrom: docker.io/${{ inputs.repository }}:${{ inputs.tag }}
        # Set platform to an empty string when using self-hosted runners so
        # devcontainers/ci doesn't try to use skopeo (ubuntu 20.10+ only)
        platform: ${{ contains(runner.name, 'rapidsai') != true && format('linux/{0}', inputs.arch) || '' }}
