name: Build and test devcontainer images

on:
  workflow_call:
    inputs:
      home:
        type: string
        required: true
        description: Runner HOME dir
      CUDA:
        type: string
        required: true
      LLVM:
        type: string
        required: true
      RUST:
        type: string
        required: true
      NVHPC:
        type: string
        required: true
      MAMBA:
        type: string
        required: true

jobs:

  build-and-test:
    name: Test
    runs-on:
      - self-hosted
      - linux
      - ${{ matrix.arch }}
      - cpu4
    permissions:
      packages: write
    strategy:
      fail-fast: true
      matrix:
        arch: [amd64, arm64]
    steps:
      - name: Checkout ${{ github.repository }}
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          persist-credentials: false

      - uses: ./.github/actions/copy-common-scripts

      - id: info
        name: Determine devcontainer image info
        uses: ./.github/actions/image-info
        with:
          CUDA: "${{ inputs.CUDA }}"
          LLVM: "${{ inputs.LLVM }}"
          RUST: "${{ inputs.RUST }}"
          NVHPC: "${{ inputs.NVHPC }}"
          MAMBA: "${{ inputs.MAMBA }}"

      - name: Build and test ${{ steps.info.outputs.tag }}-${{ matrix.arch }}
        uses: ./.github/actions/build-and-test-image
        with:
          home: "${{ inputs.home }}"
          arch: "${{ matrix.arch }}"
          dir: "${{ steps.info.outputs.dir }}"
          tag: "${{ steps.info.outputs.tag }}"
