name: Build and test devcontainer images

on:
  workflow_call:
    inputs:
      CUDA:
        type: string
        required: true
      LLVM:
        type: string
        required: true
      RUST:
        type: string
        required: true
      NVHPC:
        type: string
        required: true
      MAMBA:
        type: string
        required: true

jobs:

  build-and-test:
    name: Test
    runs-on: ubuntu-latest
    permissions:
      packages: write
    strategy:
      max-parallel: 2
      fail-fast: true
      matrix:
        arch: [amd64, arm64]
    steps:
      - name: Checkout ${{ github.repository }}
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - uses: ./.github/actions/copy-common-scripts

      - name: Determine devcontainer image info
        uses: ./.github/actions/image-info
        with: ${{ fromJSON(inputs) }}
        id: info

      - name: Build and test ${{ steps.info.outputs.tag }}-${{ matrix.arch }}
        uses: ./.github/actions/build-and-test-image
        with:
          home: "${{ env.HOME }}"
          arch: "${{ matrix.arch }}"
          dir: "${{ steps.info.outputs.dir }}"
          tag: "${{ steps.info.outputs.tag }}"
