name: Build and push devcontainer images

on:
  workflow_call:
    inputs:
      CUDA:
        type: string
        required: true
      LLVM:
        type: string
        required: true
      RUST:
        type: string
        required: true
      NVHPC:
        type: string
        required: true
      MAMBA:
        type: string
        required: true

jobs:

  build-and-push:
    name: Build and push to ghcr.io
    runs-on: ${{ fromJSON(github.repository != 'rapidsai/devcontainers' && '"ubuntu-latest"' || format('{{"labels":["self-hosted", "linux", "{0}", "cpu4"]}}', matrix.arch)) }}
    permissions:
      packages: write
    outputs:
      dir: ${{ steps.info.outputs.dir }}
      tag: ${{ steps.info.outputs.tag }}
    strategy:
      fail-fast: false
      matrix:
        arch: [amd64, arm64]
    steps:
      - name: Checkout ${{ github.repository }}
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          persist-credentials: false

      - id: info
        name: Determine devcontainer image info
        uses: ./.github/actions/image-info
        with:
          CUDA: "${{ inputs.CUDA }}"
          LLVM: "${{ inputs.LLVM }}"
          RUST: "${{ inputs.RUST }}"
          NVHPC: "${{ inputs.NVHPC }}"
          MAMBA: "${{ inputs.MAMBA }}"

      - name: Build and push ${{ steps.info.outputs.tag }}-${{ matrix.arch }}
        uses: ./.github/actions/build-and-push-image
        with:
          arch: "${{ matrix.arch }}"
          dir: "${{ steps.info.outputs.dir }}"
          tag: "${{ steps.info.outputs.tag }}"
          repository: "${{ vars.DOCKERHUB_REPOSITORY }}"

  push-to-dockerhub:
    name: Push to Docker Hub
    needs: build-and-push
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - name: Checkout ${{ github.repository }}
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Push multiarch manifest to Docker Hub
        uses: ./.github/actions/push-to-dockerhub
        with:
          archs: amd64 arm64
          repository: "${{ vars.DOCKERHUB_REPOSITORY }}"
          tag: "${{ needs.build-and-push.outputs.tag }}"
          username: "${{ secrets.GPUCIBOT_DOCKERHUB_USER }}"
          password: "${{ secrets.GPUCIBOT_DOCKERHUB_TOKEN }}"

      - continue-on-error: true
        name: Remove ghcr.io images
        uses: snok/container-retention-policy@v1
        with:
          image-names: devcontainers
          cut-off: "1 second ago UTC"
          token: "${{ github.token }}"
          org-name: "${{ github.repository_owner }}"
          filter-tags: "${{ needs.build-and-push.outputs.tag }}-*"
          account-type: ${{ github.repository == 'rapidsai/devcontainers' && 'org' || 'personal' }}
