name: Build and push devcontainer images

on:
  workflow_call:
    inputs:
      home:
        type: string
        required: true
        description: Runner HOME dir
      CUDA:
        type: string
        required: true
      LLVM:
        type: string
        required: true
      RUST:
        type: string
        required: true
      NVHPC:
        type: string
        required: true
      MAMBA:
        type: string
        required: true
      RAPIDS:
        type: string
        required: true
        description: RAPIDS release version

jobs:

  build-and-push:
    name: Push
    runs-on:
      - self-hosted
      - linux
      - ${{ matrix.arch }}
      - cpu4
    permissions:
      packages: write
    strategy:
      fail-fast: true
      matrix:
        arch: [amd64, arm64]
    steps:
      - name: Checkout ${{ github.repository }}
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          persist-credentials: false

      - uses: ./.github/actions/copy-common-scripts

      - id: info
        name: Determine devcontainer image info
        uses: ./.github/actions/image-info
        with:
          CUDA: "${{ inputs.CUDA }}"
          LLVM: "${{ inputs.LLVM }}"
          RUST: "${{ inputs.RUST }}"
          NVHPC: "${{ inputs.NVHPC }}"
          MAMBA: "${{ inputs.MAMBA }}"
          RAPIDS: "${{ inputs.RAPIDS }}"

      - name: Build and push ${{ steps.info.outputs.tag }}-${{ matrix.arch }}
        uses: ./.github/actions/build-and-push-image
        with:
          home: "${{ inputs.home }}"
          arch: "${{ matrix.arch }}"
          dir: "${{ steps.info.outputs.dir }}"
          tag: "${{ steps.info.outputs.tag }}"

  push-to-dockerhub:
    name: Push to Docker Hub
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ${{ github.repository }}
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          persist-credentials: false

      - id: info
        name: Determine devcontainer image info
        uses: ./.github/actions/image-info
        with:
          CUDA: "${{ inputs.CUDA }}"
          LLVM: "${{ inputs.LLVM }}"
          RUST: "${{ inputs.RUST }}"
          NVHPC: "${{ inputs.NVHPC }}"
          MAMBA: "${{ inputs.MAMBA }}"
          RAPIDS: "${{ inputs.RAPIDS }}"

      - name: Push multiarch manifest to Docker Hub
        uses: ./.github/actions/push-to-dockerhub
        with:
          archs: "amd64 arm64"
          home: "${{ env.HOME }}"
          tag: "${{ steps.info.outputs.tag }}"
          username: "${{ secrets.GPUCIBOT_DOCKERHUB_USER }}"
          password: "${{ secrets.GPUCIBOT_DOCKERHUB_TOKEN }}"
