name: Build and test devcontainer images

on:
  workflow_call:
    inputs:
      os:
        type: string
        required: true
        description: Image OS
      repo:
        type: string
        required: true
        description: Image repo
      features:
        type: string
        required: true
        description: JSON list of devcontainer features
      container_env:
        type: string
        required: false
        description: JSON map of default envvars to build into the devcontainer

env:
  cl: "${{ fromJSON(inputs.features)[1].version }}"
  cuda: "${{ fromJSON(inputs.features)[0].version }}"

jobs:

  build-and-test-windows:
    name: Build and test (${{ matrix.edition }})
    runs-on: ${{ matrix.runner }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - { runner: windows-2019, edition: "2019" }
          - { runner: windows-2022, edition: "2022" }
    steps:
      - name: Checkout ${{ github.repository }}
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          persist-credentials: false

      - id: info
        name: Get container info
        shell: bash
        run: |
          repo="${{ inputs.repo }}"
          version="$(git describe --abbrev=0 --tags | sed 's/[a-zA-Z]//g' | cut -d '.' -f -2)"
          cat <<EOF | tee "$GITHUB_ENV"
          repo=${repo,,}
          version=${version}
          tag=${version}-cuda${cuda}-cl${cl}-${{ inputs.os }}${{ matrix.edition }}
          EOF

      - name: Build ${{ env.tag }}
        uses: ./.github/actions/build-windows-image
        with:
          cl: "${{ env.cl }}"
          tag: "${{ env.tag }}"
          cuda: "${{ env.cuda }}"
          repo: "${{ env.repo }}"
          version: "${{ env.version }}"
          edition: "${{ matrix.edition }}"

      - name: Test ${{ env.tag }}
        uses: ./.github/actions/test-windows-image
        with:
          cl: "${{ env.cl }}"
          tag: "${{ env.tag }}"
          cuda: "${{ env.cuda }}"
          repo: "${{ env.repo }}"
          version: "${{ env.version }}"
          edition: "${{ matrix.edition }}"
