name: Build and push devcontainer images

on:
  workflow_call:
    inputs:
      CPP:
        type: string
        required: true
      CUDA:
        type: string
        required: true
      LLVM:
        type: string
        required: true
      RUST:
        type: string
        required: true
      NVHPC:
        type: string
        required: true
      MAMBAFORGE:
        type: string
        required: true

jobs:

  build-and-upload:
    name: Build and upload
    runs-on: ${{ fromJSON(github.repository != 'rapidsai/devcontainers' && '"ubuntu-latest"' || format('"linux-{0}-cpu4"', matrix.arch)) }}
    permissions:
      packages: write
    outputs:
      dir: ${{ steps.info.outputs.dir }}
      repo: ${{ steps.build.outputs.repo }}
    strategy:
      fail-fast: false
      matrix:
        arch: [amd64, arm64]
    steps:
      - name: Checkout ${{ github.repository }}
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          persist-credentials: false

      - id: info
        name: Determine devcontainer image info
        uses: ./.github/actions/image-info
        with:
          CPP: "${{ inputs.CPP }}"
          CUDA: "${{ inputs.CUDA }}"
          LLVM: "${{ inputs.LLVM }}"
          RUST: "${{ inputs.RUST }}"
          NVHPC: "${{ inputs.NVHPC }}"
          MAMBAFORGE: "${{ inputs.MAMBAFORGE }}"

      - id: build
        name: Build ${{ steps.json.outputs.tag }}-${{ matrix.arch }}
        uses: ./.github/actions/build-image
        with:
          arch: "${{ matrix.arch }}"
          dir: "${{ steps.info.outputs.dir }}"
          tag: "${{ steps.json.outputs.tag }}"
          repo: "${{ vars.DOCKERHUB_REPOSITORY || github.repository }}"

      - name: Upload ${{ steps.json.outputs.tag }}-${{ matrix.arch }}
        uses: actions/upload-artifact@v3
        with:
          retention-days: 1
          name: ${{ steps.json.outputs.tag }}
          path: ${{ runner.temp }}/${{ matrix.arch }}.tar

  push-to-dockerhub:
    name: Push to Docker Hub
    needs: build-and-upload
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - name: Checkout ${{ github.repository }}
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Free up disk space
        uses: ./.github/actions/free-disk-space
        with:
          tool_cache: "${{ runner.tool_cache }}"

      - name: Download ${{ needs.build-and-upload.outputs.tag }}
        uses: actions/download-artifact@v3
        with:
          name: ${{ needs.build-and-upload.outputs.tag }}
          path: ${{ runner.temp }}

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.GPUCIBOT_DOCKERHUB_USER }}
          password: ${{ secrets.GPUCIBOT_DOCKERHUB_TOKEN }}

      - name: Push multiarch manifest to Docker Hub
        shell: bash --noprofile --norc -x -eo pipefail {0}
        env:
          name: "${{ needs.build-and-upload.outputs.repo }}:${{ needs.build-and-upload.outputs.tag }}"
        run: |

          find "${{ runner.temp }}/" -type f -name '*.tar';

          docker manifest rm ${name} || true;

          hashes=();

          for arch in "amd64" "arm64"; do
            # Load and push the linux/$arch image and read its local hash
            hash="$(docker load --input "${{ runner.temp }}/${arch}.tar" | tail -n1 | cut -d':' -f3)";
            # Tag the loaded image with the final name
            docker image tag ${hash} ${name};
            # Push the local image to the registry to get its remote hash
            hash="$(docker push ${name} | tail -n1 | cut -d' ' -f3)";
            # Save the remote hash for use below
            hashes+=("$hash");
          done

          # Create and push the multiarch manifest
          docker buildx imagetools create --tag ${name} ${hashes[@]};
