name: Clean up ghcr.io packages

on:
  workflow_dispatch:
    inputs:
      cut-off:
        default: "1 second ago UTC"
        description: >
          Delete images older than this datetime (must include timezone).
          Accepted formats: dateparser.readthedocs.io

jobs:
  cleanup-ghcr:
    name: Clean up ghcr.io packages
    runs-on: ubuntu-latest
    steps:
      # Needs PAT with repo and {read,delete}:packages scopes
      - name: Clean up ghcr.io packages
        uses: snok/container-retention-policy@v1
        with:
          image-names: devcontainers
          cut-off: "${{ inputs.cut-off }}"
          token: "${{ secrets.WORKFLOW_TOKEN }}"
          org-name: "${{ github.repository_owner }}"
          account-type: ${{ github.repository == 'rapidsai/devcontainers' && 'org' || 'personal' }}
