name: Release

concurrency:
  group: release-on-${{ github.event_name }}-from-${{ github.ref_name }}
  cancel-in-progress: true

on:
  workflow_dispatch:

jobs:

  release-features:
    name: Release Features
    secrets: inherit
    uses: ./.github/workflows/release-features.yml

  image-matrix:
    name: Determine image matrix
    runs-on: ubuntu-latest
    outputs:
      linux: ${{ steps.matrix.outputs.linux }}
      windows: ${{ steps.matrix.outputs.windows }}
    steps:
      - name: Checkout ${{ github.repository }}
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          persist-credentials: false

      - id: matrix
        name: Determine image matrix
        uses: ./.github/actions/image-matrix
        with:
          full_matrix: 'true'

  build-and-push-linux-images:
    name: ${{ matrix.name }}
    needs: image-matrix
    secrets: inherit
    uses: ./.github/workflows/build-and-push-linux-image.yml
    strategy:
      fail-fast: false
      matrix: ${{ fromJSON(needs.image-matrix.outputs.linux) }}
    with:
      os : "${{ matrix.os }}"
      features: "${{ toJSON(matrix.features) }}"
      container_env: "${{ toJSON(matrix.env) }}"
      repo: "${{ vars.DOCKERHUB_REPOSITORY || github.repository }}"

  # build-and-push-windows-images:
  #   name: ${{ matrix.name }}
  #   needs: image-matrix
  #   secrets: inherit
  #   uses: ./.github/workflows/build-and-push-windows-image.yml
  #   strategy:
  #     fail-fast: false
  #     matrix: ${{ fromJSON(needs.image-matrix.outputs.windows) }}
  #   with:
  #     os : "${{ matrix.os }}"
  #     features: "${{ toJSON(matrix.features) }}"
  #     container_env: "${{ toJSON(matrix.env) }}"
  #     repo: "${{ vars.DOCKERHUB_REPOSITORY || github.repository }}"
