name: Release

concurrency:
  group: release-on-${{ github.event_name }}-from-${{ github.ref_name }}
  cancel-in-progress: true

on:
  workflow_dispatch:

jobs:

  release-features:
    name: Release Features
    secrets: inherit
    uses: ./.github/workflows/release-features.yml

  image-matrix:
    name: Determine image matrix
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.matrix.outputs.matrix }}
    steps:
      - name: Checkout ${{ github.repository }}
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          persist-credentials: false

      - id: matrix
        name: Determine image matrix
        uses: ./.github/actions/image-matrix
        with:
          full_matrix: 'true'

  build-and-push-images:
    name: ${{ matrix.name }}
    needs: image-matrix
    secrets: inherit
    uses: ./.github/workflows/build-and-push-image.yml
    strategy:
      fail-fast: false
      matrix: ${{ fromJSON(needs.image-matrix.outputs.matrix) }}
    with:
      os : "${{ matrix.os }}"
      features: "${{ toJSON(matrix.features) }}"
