name: Release Windows

concurrency:
  group: release-windows-from-${{ github.ref_name }}
  cancel-in-progress: true

on:
  workflow_call:
    inputs:
      full_matrix:
        type: boolean
        default: false
        description: Release all images
  workflow_dispatch:
    inputs:
      full_matrix:
        type: boolean
        default: true
        description: Release all images

jobs:

  image-matrix:
    name: Determine image matrix
    runs-on: ubuntu-latest
    outputs:
      windows: ${{ steps.matrix.outputs.windows }}
    steps:
      - name: Checkout ${{ github.repository }}
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false

      - id: matrix
        name: Determine image matrix
        uses: ./.github/actions/image-matrix
        with:
          full_matrix: "${{ inputs.full_matrix && 'true' || 'false' }}"

  release-windows:
    if: needs.image-matrix.outputs.windows != '{"include":[]}'
    name: ${{ matrix.name }}
    needs: image-matrix
    secrets: inherit
    uses: ./.github/workflows/build-test-and-push-windows-image.yml
    strategy:
      fail-fast: false
      matrix: ${{ fromJSON(needs.image-matrix.outputs.windows) }}
    with:
      push: true
      os: "${{ matrix.os }}"
      features: "${{ toJSON(matrix.features) }}"
      container_env: "${{ toJSON(matrix.env) }}"
      repo: "${{ vars.DOCKERHUB_REPOSITORY || github.repository }}"
