name: Release

concurrency:
  group: release-on-${{ github.event_name }}-from-${{ github.ref_name }}
  cancel-in-progress: true

on:
  workflow_dispatch:

jobs:

  release-features:
    name: Release Features
    secrets: inherit
    uses: ./.github/workflows/release-features.yml

  image-matrix:
    name: Determine image matrix
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.matrix.outputs.matrix }}
    steps:
      - name: Checkout ${{ github.repository }}
        uses: actions/checkout@v3
        with:
          persist-credentials: false
      - id: matrix
        name: Determine image matrix
        uses: ./.github/actions/image-matrix

  push-images:
    name: Image
    needs: image-matrix
    secrets: inherit
    uses: ./.github/workflows/build-and-push-image.yml
    strategy:
      fail-fast: false
      matrix: ${{ fromJSON(needs.image-matrix.outputs.matrix) }}
    with:
      CPP: "${{ matrix.CPP }}"
      CUDA: "${{ matrix.CUDA }}"
      LLVM: "${{ matrix.LLVM }}"
      RUST: "${{ matrix.RUST }}"
      NVHPC: "${{ matrix.NVHPC }}"
      MAMBA: "${{ matrix.MAMBA }}"

  cleanup-ghcr:
    name: Clean up ghcr.io packages
    needs: push-images
    secrets: inherit
    uses: ./.github/workflows/cleanup-ghcr.yml
    with:
      cut-off: "1 second ago UTC"
      untagged-only: true
