name: Release

concurrency:
  group: release-from-${{ github.ref_name }}
  cancel-in-progress: true

on:
  workflow_dispatch:
  push:
    branches:
      - "branch-[0-9][0-9].[0-9][0-9]"
    tags:
      - "v[0-9][0-9].[0-9][0-9].[0-9][0-9]"

jobs:

  release-linux:
    name: Linux
    secrets: inherit
    uses: ./.github/workflows/release-linux.yml
    with:
      full_matrix: ${{ github.event_name == 'workflow_dispatch' }}

  release-windows:
    name: Windows
    secrets: inherit
    uses: ./.github/workflows/release-windows.yml
    with:
      full_matrix: ${{ github.event_name == 'workflow_dispatch' }}

  release-features:
    name: Features
    secrets: inherit
    uses: ./.github/workflows/release-features.yml
