name: Release features

on:
  workflow_call:
  workflow_dispatch:

jobs:

  release-features:
    name: Release features
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - name: Checkout ${{ github.repository }}
        uses: actions/checkout@v4

      - name: Copy common scripts into features
        uses: ./.github/actions/copy-common-scripts

      - name: Install devcontainers CLI
        uses: ./.github/actions/install-devcontainers-cli

      - name: Release features
        uses: devcontainers/action@v1
        with:
          generate-docs: "true"
          publish-features: "true"
          disable-repo-tagging: "true"
          base-path-to-features: "./features/src"
          features-namespace: "${{ github.repository }}/features"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
