name: Test

concurrency:
  group: test-on-${{ github.event_name }}-from-${{ github.ref_name }}
  cancel-in-progress: true

on:
  pull_request:

jobs:

  validate-features-json:
    name: Validate features
    secrets: inherit
    uses: ./.github/workflows/validate-features-json.yml

  run-feature-integration-tests:
    name: Integration
    needs: validate-features-json
    secrets: inherit
    uses: ./.github/workflows/build-and-test-feature.yml
    with:
      name: "Test global scenarios"
      args: "--global-scenarios-only"

  features-matrix:
    name: Determine features matrix
    needs: validate-features-json
    runs-on: ubuntu-latest
    outputs:
      features: ${{ steps.matrix.outputs.features }}
      scenarios: ${{ steps.matrix.outputs.scenarios }}
    steps:
      - name: Checkout ${{ github.repository }}
        uses: actions/checkout@v3
        with:
          persist-credentials: false
      - id: matrix
        name: Determine features matrix
        uses: ./.github/actions/feature-matrix

  run-feature-scenario-tests:
    name: Feature
    needs: features-matrix
    secrets: inherit
    uses: ./.github/workflows/build-and-test-feature.yml
    strategy:
      fail-fast: true
      matrix:
        feature: ${{ fromJSON(needs.features-matrix.outputs.scenarios) }}
    with:
      name: "'${{ matrix.feature }}' scenarios"
      args: "-f ${{ matrix.feature }} --skip-autogenerated"

  run-generated-feature-tests:
    name: Feature
    needs: features-matrix
    secrets: inherit
    uses: ./.github/workflows/build-and-test-feature.yml
    strategy:
      fail-fast: true
      matrix:
        feature: ${{ fromJSON(needs.features-matrix.outputs.features) }}
        image: ["ubuntu:jammy", "mcr.microsoft.com/devcontainers/base:jammy"]
    with:
      name: "'${{ matrix.feature }}' × '${{ matrix.image }}'"
      args: "--skip-scenarios -f ${{ matrix.feature }} -i ${{ matrix.image }}"

  image-matrix:
    name: Determine image matrix
    needs:
      - validate-features-json
      - run-feature-scenario-tests
      - run-generated-feature-tests
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.matrix.outputs.matrix }}
    steps:
      - name: Checkout ${{ github.repository }}
        uses: actions/checkout@v3
        with:
          persist-credentials: false
      - id: matrix
        name: Determine image matrix
        uses: ./.github/actions/image-matrix

  test-images:
    name: Image
    needs: image-matrix
    secrets: inherit
    uses: ./.github/workflows/build-and-test-image.yml
    strategy:
      fail-fast: true
      matrix: ${{ fromJSON(needs.image-matrix.outputs.matrix) }}
    with:
      CUDA: "${{ matrix.CUDA }}"
      LLVM: "${{ matrix.LLVM }}"
      RUST: "${{ matrix.RUST }}"
      NVHPC: "${{ matrix.NVHPC }}"
      MAMBA: "${{ matrix.MAMBA }}"
