name: Test features

concurrency:
  group: test-features-on-${{ github.event_name }}-from-${{ github.ref }}
  cancel-in-progress: true

on:
  pull_request:

jobs:

  matrix:
    name: Determine matrix
    runs-on: ubuntu-latest
    outputs:
      features: ${{ steps.matrix.outputs.features }}
      scenarios: ${{ steps.matrix.outputs.scenarios }}
    steps:
      - name: Checkout ${{ github.repository }}
        uses: actions/checkout@v3
        with:
          persist-credentials: false
      - id: matrix
        name: Determine matrix
        uses: ./.github/actions/feature-matrix

  test-global:
    name: Global
    uses: ./.github/workflows/build-and-test-feature.yml
    secrets: inherit
    with:
      name: "Global scenarios"
      args: "--global-scenarios-only"

  test-scenario:
    needs: matrix
    name: Scenarios
    uses: ./.github/workflows/build-and-test-feature.yml
    secrets: inherit
    strategy:
      fail-fast: true
      matrix:
        feature: ${{ fromJSON(needs.matrix.outputs.scenarios) }}
    with:
      name: "'${{ matrix.feature }}' scenario tests"
      args: "-f ${{ matrix.feature }} --skip-autogenerated"

  test-generated:
    needs: matrix
    name: Generated
    uses: ./.github/workflows/build-and-test-feature.yml
    secrets: inherit
    strategy:
      fail-fast: true
      matrix:
        feature: ${{ fromJSON(needs.matrix.outputs.features) }}
        image: ["ubuntu:jammy", "mcr.microsoft.com/devcontainers/base:jammy"]
    with:
      name: "'${{ matrix.feature }}' against '${{ matrix.image }}' tests"
      args: "--skip-scenarios -f ${{ matrix.feature }} -i ${{ matrix.image }}"
