name: Test Windows

on:
  workflow_call:

jobs:
  version-and-changes:
    name: Check if files changed and get repo version
    runs-on: ubuntu-latest
    outputs:
      any_changed: ${{ steps.changes.outputs.any_changed }}
      repo_version: ${{ steps.version.outputs.repo_version }}
    steps:
      - name: Checkout ${{ github.repository }}
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          persist-credentials: false

      - id: get-pr-info
        if: inputs.full_matrix != 'true'
        name: Get PR target branch info
        uses: ./.github/actions/get-pr-info

      - id: version
        name: Get the repository version from the closest git tag
        shell: bash
        run: |
          cat <<EOF | tee "$GITHUB_OUTPUT"
          repo_version=$(git describe --abbrev=0 --tags | sed 's/[a-zA-Z]//g' | cut -d '.' -f -2)
          EOF

      - id: changes
        name: Check if files changed
        if: inputs.full_matrix != 'true'
        uses: tj-actions/changed-files@v35.4.4
        with:
          base_sha: ${{ fromJSON(steps.get-pr-info.outputs.pr-info).base.sha }}
          files: |
            .github/**/*windows*
            scripts/windows/**

  dispatch:
    needs: version-and-changes
    if: needs.version-and-changes.outputs.any_changed == 'true'
    name: Build
    uses: ./.github/workflows/dispatch-windows.yml
    secrets: inherit
    with:
      push_image: false
      repo_version: ${{ needs.version-and-changes.outputs.repo_version }}
