name: Test

concurrency:
  group: test-on-${{ github.event_name }}-from-${{ github.ref_name }}
  cancel-in-progress: true

on:
  pull_request:
  push:
    branches:
      - "pull-request/[0-9]+"

jobs:
  check-event:
    name: Check PR Event
    runs-on: ubuntu-latest
    outputs:
      ok: ${{ steps.check_pr_event.outputs.ok }}
    steps:
      - id: check_pr_event
        name: Check PR Event
        shell: bash
        run: |
          [[ '${{ github.event_name }}' == 'push' && '${{ github.repository }}' == 'rapidsai/devcontainers' ]] || \
          [[ '${{ github.event_name }}' == 'pull_request' && '${{ github.repository }}' != 'rapidsai/devcontainers' ]] \
          && echo "ok=true"  | tee -a $GITHUB_OUTPUT \
          || echo "ok=false" | tee -a $GITHUB_OUTPUT;

  validate-features-json:
    if: needs.check-event.outputs.ok == 'true'
    name: Validate features
    needs: check-event
    secrets: inherit
    uses: ./.github/workflows/validate-features-json.yml

  features-matrix:
    name: Determine features matrix
    needs: validate-features-json
    runs-on: ubuntu-latest
    outputs:
      features: ${{ steps.matrix.outputs.features }}
      scenarios: ${{ steps.matrix.outputs.scenarios }}
    steps:
      - name: Checkout ${{ github.repository }}
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Copy common scripts into features
        uses: ./.github/actions/copy-common-scripts

      - id: matrix
        name: Determine features matrix
        uses: ./.github/actions/feature-matrix

  run-feature-integration-tests:
    if: needs.features-matrix.outputs.features != '[]' || needs.features-matrix.outputs.scenarios != '[]'
    name: Integration
    needs: features-matrix
    secrets: inherit
    uses: ./.github/workflows/build-and-test-feature.yml
    with:
      name: "Test global scenarios"
      args: "--global-scenarios-only"

  run-feature-scenario-tests:
    if: needs.features-matrix.outputs.scenarios != '[]'
    name: Test scenarios
    needs: features-matrix
    secrets: inherit
    uses: ./.github/workflows/build-and-test-feature.yml
    strategy:
      fail-fast: false
      matrix:
        feature: ${{ fromJSON(needs.features-matrix.outputs.scenarios) }}
    with:
      name: "Run scenario tests"
      args: "-f ${{ matrix.feature }} --skip-autogenerated"

  run-generated-feature-tests:
    if: needs.features-matrix.outputs.features != '[]'
    name: Test feature
    needs: features-matrix
    secrets: inherit
    uses: ./.github/workflows/build-and-test-feature.yml
    strategy:
      fail-fast: false
      matrix:
        feature: ${{ fromJSON(needs.features-matrix.outputs.features) }}
    with:
      name: "Run generated tests"
      args: "--skip-scenarios -f ${{ matrix.feature }} -i ubuntu:22.04"

  image-matrix:
    name: Determine image matrix
    needs: features-matrix
    runs-on: ubuntu-latest
    outputs:
      linux: ${{ steps.matrix.outputs.linux }}
      windows: ${{ steps.matrix.outputs.windows }}
    steps:
      - name: Checkout ${{ github.repository }}
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false

      - id: matrix
        name: Determine image matrix
        uses: ./.github/actions/image-matrix
        with:
          full_matrix: 'false'
          features: "${{ needs.features-matrix.outputs.features }}"
          scenarios: "${{ needs.features-matrix.outputs.scenarios }}"

  build-and-test-linux-images:
    if: needs.image-matrix.outputs.linux != '{"include":[]}'
    name: ${{ matrix.name }}
    needs: image-matrix
    secrets: inherit
    uses: ./.github/workflows/build-test-and-push-linux-image.yml
    strategy:
      fail-fast: false
      matrix: ${{ fromJSON(needs.image-matrix.outputs.linux) }}
    with:
      push: 'false'
      os: "${{ matrix.os }}"
      features: "${{ toJSON(matrix.features) }}"
      container_env: "${{ toJSON(matrix.env) }}"
      repo: "${{ vars.DOCKERHUB_REPOSITORY || github.repository }}"

  build-and-test-windows-images:
    if: needs.image-matrix.outputs.windows != '{"include":[]}'
    name: ${{ matrix.name }}
    needs: image-matrix
    secrets: inherit
    uses: ./.github/workflows/build-test-and-push-windows-image.yml
    strategy:
      fail-fast: false
      matrix: ${{ fromJSON(needs.image-matrix.outputs.windows) }}
    with:
      push: 'false'
      os: "${{ matrix.os }}"
      features: "${{ toJSON(matrix.features) }}"
      container_env: "${{ toJSON(matrix.env) }}"
      repo: "${{ vars.DOCKERHUB_REPOSITORY || github.repository }}"

  build-all-rapids-repos:
    name: Build all RAPIDS repos
    if: needs.check-event.outputs.ok == 'true'
    needs: check-event
    secrets: inherit
    uses: ./.github/workflows/build-all-rapids-repos.yml
