name: Validate features

concurrency:
  group: validate-features-on-${{ github.event_name }}-from-${{ github.ref_name }}
  cancel-in-progress: true

on:
  pull_request:

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ${{ github.repository }}
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - uses: ./.github/actions/install-devcontainers-cli

      - name: Validate devcontainer-feature.json files
        uses: devcontainers/action@v1
        with:
          validate-only: "true"
          base-path-to-features: "./features/src"
