name: Validate features

on:
  workflow_call:

jobs:
  validate:
    name: Validate features
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ${{ github.repository }}
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Install devcontainers CLI
        uses: ./.github/actions/install-devcontainers-cli

      - name: Validate devcontainer-feature.json files
        uses: devcontainers/action@v1
        with:
          validate-only: "true"
          base-path-to-features: "./features/src"
